spring:
  profiles: cloud
  datasource:
    url: ${vcap.services.${db_service_instance_name}.credentials.url}
    username: ${vcap.services.${db_service_instance_name}.credentials.user}
    password: ${vcap.services.${db_service_instance_name}.credentials.password}
    driver-class-name: ${vcap.services.${db_service_instance_name}.credentials.driver}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximumPoolSize: 10