spring:
  profiles: local
  datasource:
    url:
    username:
    password:
    driver-class-name: com.sap.db.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 1
